name: CI
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
            cd {{ secrets.WORKING_DIR }}
            && git pull
            && source {{ WORKING_DIR }}/.venv/bin/activate
            && pip install -r requirements.txt
            && systemctl restart tindegram
